<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="16.0.0" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="17.0.0-rc4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Our.Umbraco.MaintenanceMode.Core\Our.Umbraco.MaintenanceMode.Core.csproj" />
	</ItemGroup>

</Project>
