// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSettingsData, GetSettingsErrors, GetSettingsResponses, GetStatusData, GetStatusErrors, GetStatusResponses, GetToggleAccessData, GetToggleAccessErrors, GetToggleAccessResponses, GetToggleFrozenData, GetToggleFrozenErrors, GetToggleFrozenResponses, GetToggleModeData, GetToggleModeErrors, GetToggleModeResponses, GetToggleSiteLockData, GetToggleSiteLockErrors, GetToggleSiteLockResponses, PostSaveSettingsData, PostSaveSettingsErrors, PostSaveSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postSaveSettings = <ThrowOnError extends boolean = false>(options: Options<PostSaveSettingsData, ThrowOnError>) => (options.client ?? client).post<PostSaveSettingsResponses, PostSaveSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/SaveSettings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/Settings',
    ...options
});

export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => (options?.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/Status',
    ...options
});

export const getToggleAccess = <ThrowOnError extends boolean = false>(options?: Options<GetToggleAccessData, ThrowOnError>) => (options?.client ?? client).get<GetToggleAccessResponses, GetToggleAccessErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/ToggleAccess',
    ...options
});

export const getToggleFrozen = <ThrowOnError extends boolean = false>(options?: Options<GetToggleFrozenData, ThrowOnError>) => (options?.client ?? client).get<GetToggleFrozenResponses, GetToggleFrozenErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/ToggleFrozen',
    ...options
});

// NOTE: manually mirrored to match the backend ToggleSiteLock endpoint; regenerate via openapi-ts when the backend is available.
export const getToggleSiteLock = <ThrowOnError extends boolean = false>(options?: Options<GetToggleSiteLockData, ThrowOnError>) => (options?.client ?? client).get<GetToggleSiteLockResponses, GetToggleSiteLockErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/ToggleSiteLock',
    ...options
});

export const getToggleMode = <ThrowOnError extends boolean = false>(options?: Options<GetToggleModeData, ThrowOnError>) => (options?.client ?? client).get<GetToggleModeResponses, GetToggleModeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/maintenance/api/v1/ToggleMode',
    ...options
});
