// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44328/' | (string & {});
};

export type MaintenanceMode = {
    pageTitle?: null | string;
    title?: null | string;
    text?: null | string;
};

export type MaintenanceModeSettings = {
    allowBackOfficeUsersThrough: boolean;
    templateName?: null | string;
    urlWhitelist?: null | string;
    ipWhitelist?: null | string;
    unfrozenUsers?: null | string;
    viewModel?: MaintenanceMode;
};

export type MaintenanceModeStatus = {
    isInMaintenanceMode: boolean;
    settings?: MaintenanceModeSettings;
    isContentFrozen: boolean;
};

export type PostSaveSettingsData = {
    body: MaintenanceModeSettings;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/SaveSettings';
};

export type PostSaveSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostSaveSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/Settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: MaintenanceModeSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/Status';
};

export type GetStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: MaintenanceModeStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetToggleAccessData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleAccess';
};

export type GetToggleAccessErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetToggleAccessResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetToggleFrozenData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleFrozen';
};

export type GetToggleFrozenErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetToggleFrozenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetToggleModeData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleMode';
};

export type GetToggleModeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetToggleModeResponses = {
    /**
     * OK
     */
    200: unknown;
};
