// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type MaintenanceMode = {
    pageTitle?: string | null;
    title?: string | null;
    text?: string | null;
};

export type MaintenanceModeSettings = {
    allowBackOfficeUsersThrough: boolean;
    templateName?: string | null;
    urlWhitelist?: string | null;
    unfrozenUsers?: string | null;
    viewModel?: MaintenanceMode | null;
};

export type MaintenanceModeStatus = {
    isInMaintenanceMode: boolean;
    settings?: MaintenanceModeSettings | null;
    isContentFrozen: boolean;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/GetSettings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: MaintenanceModeSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/GetStatus';
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: MaintenanceModeStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type SaveSettingsData = {
    body?: MaintenanceModeSettings;
    path?: never;
    query?: never;
    url: '/umbraco/maintenance/api/v1/SaveSettings';
};

export type SaveSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ToggleAccessData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleAccess';
};

export type ToggleAccessResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ToggleFrozenData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleFrozen';
};

export type ToggleFrozenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ToggleModeData = {
    body?: never;
    path?: never;
    query?: {
        maintenanceMode?: boolean;
    };
    url: '/umbraco/maintenance/api/v1/ToggleMode';
};

export type ToggleModeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:24368' | (string & {});
};