<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Product>Our.Umbraco.MaintenanceMode</Product>
		<PackageId>Our.Umbraco.MaintenanceMode</PackageId>
		<Title>Our.Umbraco.MaintenanceMode</Title>

		<Authors>Kevin Jump,Aaron Sadler</Authors>
		<Description><![CDATA[Put Umbraco Into Maintenance Mode - While you do things]]></Description>

		<PackageTags>umbraco plugin package umbraco-marketplace</PackageTags>
		<RootNamespace>Our.Umbraco.MaintenanceMode</RootNamespace>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<PackageIcon>maintenance-icon.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
		<None Include="maintenance-icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms" Version="18.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Our.Umbraco.MaintenanceMode.Core\Our.Umbraco.MaintenanceMode.Core.csproj" />
		<ProjectReference Include="..\Our.Umbraco.MaintenanceMode.Client\Our.Umbraco.MaintenanceMode.Client.csproj" />
	</ItemGroup>

</Project>
